/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SightSound.TicketingSDK.Client.OpenAPIDateConverter;

namespace SightSound.TicketingSDK.Model
{
    /// <summary>
    /// Defines ChallengeIndicatorEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ChallengeIndicatorEnum
    {
        /// <summary>
        /// Enum NoPreference for value: noPreference
        /// </summary>
        [EnumMember(Value = "noPreference")]
        NoPreference = 1,

        /// <summary>
        /// Enum RequestChallenge for value: requestChallenge
        /// </summary>
        [EnumMember(Value = "requestChallenge")]
        RequestChallenge = 2,

        /// <summary>
        /// Enum RequestNoChallenge for value: requestNoChallenge
        /// </summary>
        [EnumMember(Value = "requestNoChallenge")]
        RequestNoChallenge = 3,

        /// <summary>
        /// Enum RequestChallengeAsMandate for value: requestChallengeAsMandate
        /// </summary>
        [EnumMember(Value = "requestChallengeAsMandate")]
        RequestChallengeAsMandate = 4

    }

}
