/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SightSound.TicketingSDK.Client.OpenAPIDateConverter;

namespace SightSound.TicketingSDK.Model
{
    /// <summary>
    /// DeviceRenderOptions
    /// </summary>
    [DataContract(Name = "DeviceRenderOptions")]
    public partial class DeviceRenderOptions : IEquatable<DeviceRenderOptions>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets SdkInterface
        /// </summary>
        [DataMember(Name = "sdkInterface", EmitDefaultValue = false)]
        public SdkInterfaceEnum? SdkInterface { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceRenderOptions" /> class.
        /// </summary>
        /// <param name="sdkInterface">sdkInterface.</param>
        /// <param name="sdkUiType">sdkUiType.</param>
        public DeviceRenderOptions(SdkInterfaceEnum? sdkInterface = default(SdkInterfaceEnum?), List<SdkUiTypeEnum> sdkUiType = default(List<SdkUiTypeEnum>))
        {
            this.SdkInterface = sdkInterface;
            this.SdkUiType = sdkUiType;
        }

        /// <summary>
        /// Gets or Sets SdkUiType
        /// </summary>
        [DataMember(Name = "sdkUiType", EmitDefaultValue = false)]
        public List<SdkUiTypeEnum> SdkUiType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeviceRenderOptions {\n");
            sb.Append("  SdkInterface: ").Append(SdkInterface).Append("\n");
            sb.Append("  SdkUiType: ").Append(SdkUiType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DeviceRenderOptions);
        }

        /// <summary>
        /// Returns true if DeviceRenderOptions instances are equal
        /// </summary>
        /// <param name="input">Instance of DeviceRenderOptions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeviceRenderOptions input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SdkInterface == input.SdkInterface ||
                    this.SdkInterface.Equals(input.SdkInterface)
                ) && 
                (
                    this.SdkUiType == input.SdkUiType ||
                    this.SdkUiType != null &&
                    input.SdkUiType != null &&
                    this.SdkUiType.SequenceEqual(input.SdkUiType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.SdkInterface.GetHashCode();
                if (this.SdkUiType != null)
                {
                    hashCode = (hashCode * 59) + this.SdkUiType.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
