/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SightSound.TicketingSDK.Client.OpenAPIDateConverter;

namespace SightSound.TicketingSDK.Model
{
    /// <summary>
    /// Defines ReceiptPaymentType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ReceiptPaymentType
    {
        /// <summary>
        /// Enum W for value: W
        /// </summary>
        [EnumMember(Value = "W")]
        W = 1,

        /// <summary>
        /// Enum CH for value: CH
        /// </summary>
        [EnumMember(Value = "CH")]
        CH = 2,

        /// <summary>
        /// Enum AC for value: AC
        /// </summary>
        [EnumMember(Value = "AC")]
        AC = 3,

        /// <summary>
        /// Enum CS for value: CS
        /// </summary>
        [EnumMember(Value = "CS")]
        CS = 4,

        /// <summary>
        /// Enum RF for value: RF
        /// </summary>
        [EnumMember(Value = "RF")]
        RF = 5,

        /// <summary>
        /// Enum CV for value: CV
        /// </summary>
        [EnumMember(Value = "CV")]
        CV = 6,

        /// <summary>
        /// Enum GV for value: GV
        /// </summary>
        [EnumMember(Value = "GV")]
        GV = 7,

        /// <summary>
        /// Enum NF for value: NF
        /// </summary>
        [EnumMember(Value = "NF")]
        NF = 8,

        /// <summary>
        /// Enum CR for value: CR
        /// </summary>
        [EnumMember(Value = "CR")]
        CR = 9,

        /// <summary>
        /// Enum GC for value: GC
        /// </summary>
        [EnumMember(Value = "GC")]
        GC = 10,

        /// <summary>
        /// Enum MX for value: MX
        /// </summary>
        [EnumMember(Value = "MX")]
        MX = 11

    }

}
