/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SightSound.TicketingSDK.Client.OpenAPIDateConverter;

namespace SightSound.TicketingSDK.Model
{
    /// <summary>
    /// Defines SpecialTypeCode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SpecialTypeCode
    {
        /// <summary>
        /// Enum BUYGET for value: BUY_GET
        /// </summary>
        [EnumMember(Value = "BUY_GET")]
        BUYGET = 1,

        /// <summary>
        /// Enum COMBO for value: COMBO
        /// </summary>
        [EnumMember(Value = "COMBO")]
        COMBO = 2,

        /// <summary>
        /// Enum MULTIEVENT for value: MULTI_EVENT
        /// </summary>
        [EnumMember(Value = "MULTI_EVENT")]
        MULTIEVENT = 3,

        /// <summary>
        /// Enum NET for value: NET
        /// </summary>
        [EnumMember(Value = "NET")]
        NET = 4

    }

}
