/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SightSound.TicketingSDK.Client.OpenAPIDateConverter;

namespace SightSound.TicketingSDK.Model
{
    /// <summary>
    /// Defines TransactionTypeEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransactionTypeEnum
    {
        /// <summary>
        /// Enum GoodsOrServicePurchase for value: goodsOrServicePurchase
        /// </summary>
        [EnumMember(Value = "goodsOrServicePurchase")]
        GoodsOrServicePurchase = 1,

        /// <summary>
        /// Enum CheckAcceptance for value: checkAcceptance
        /// </summary>
        [EnumMember(Value = "checkAcceptance")]
        CheckAcceptance = 2,

        /// <summary>
        /// Enum AccountFunding for value: accountFunding
        /// </summary>
        [EnumMember(Value = "accountFunding")]
        AccountFunding = 3,

        /// <summary>
        /// Enum QuasiCashTransaction for value: quasiCashTransaction
        /// </summary>
        [EnumMember(Value = "quasiCashTransaction")]
        QuasiCashTransaction = 4,

        /// <summary>
        /// Enum PrepaidActivationAndLoad for value: prepaidActivationAndLoad
        /// </summary>
        [EnumMember(Value = "prepaidActivationAndLoad")]
        PrepaidActivationAndLoad = 5

    }

}
