/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing BrowserInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BrowserInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BrowserInfo
        //private BrowserInfo instance;

        public BrowserInfoTests()
        {
            // TODO uncomment below to create an instance of BrowserInfo
            //instance = new BrowserInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BrowserInfo
        /// </summary>
        [Fact]
        public void BrowserInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" BrowserInfo
            //Assert.IsType<BrowserInfo>(instance);
        }


        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Fact]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }
        /// <summary>
        /// Test the property 'ColorDepth'
        /// </summary>
        [Fact]
        public void ColorDepthTest()
        {
            // TODO unit test for the property 'ColorDepth'
        }
        /// <summary>
        /// Test the property 'JavaEnabled'
        /// </summary>
        [Fact]
        public void JavaEnabledTest()
        {
            // TODO unit test for the property 'JavaEnabled'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'ScreenHeight'
        /// </summary>
        [Fact]
        public void ScreenHeightTest()
        {
            // TODO unit test for the property 'ScreenHeight'
        }
        /// <summary>
        /// Test the property 'ScreenWidth'
        /// </summary>
        [Fact]
        public void ScreenWidthTest()
        {
            // TODO unit test for the property 'ScreenWidth'
        }
        /// <summary>
        /// Test the property 'TimeZoneOffset'
        /// </summary>
        [Fact]
        public void TimeZoneOffsetTest()
        {
            // TODO unit test for the property 'TimeZoneOffset'
        }
        /// <summary>
        /// Test the property 'AcceptHeader'
        /// </summary>
        [Fact]
        public void AcceptHeaderTest()
        {
            // TODO unit test for the property 'AcceptHeader'
        }
        /// <summary>
        /// Test the property 'JavaScriptEnabled'
        /// </summary>
        [Fact]
        public void JavaScriptEnabledTest()
        {
            // TODO unit test for the property 'JavaScriptEnabled'
        }

    }

}
