/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing CartRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartRequest
        //private CartRequest instance;

        public CartRequestTests()
        {
            // TODO uncomment below to create an instance of CartRequest
            //instance = new CartRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartRequest
        /// </summary>
        [Fact]
        public void CartRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartRequest
            //Assert.IsType<CartRequest>(instance);
        }


        /// <summary>
        /// Test the property 'OrderNumber'
        /// </summary>
        [Fact]
        public void OrderNumberTest()
        {
            // TODO unit test for the property 'OrderNumber'
        }
        /// <summary>
        /// Test the property 'PromoCode'
        /// </summary>
        [Fact]
        public void PromoCodeTest()
        {
            // TODO unit test for the property 'PromoCode'
        }
        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [Fact]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }
        /// <summary>
        /// Test the property 'ReferenceNumber'
        /// </summary>
        [Fact]
        public void ReferenceNumberTest()
        {
            // TODO unit test for the property 'ReferenceNumber'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Fact]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }
        /// <summary>
        /// Test the property 'TicketBatch'
        /// </summary>
        [Fact]
        public void TicketBatchTest()
        {
            // TODO unit test for the property 'TicketBatch'
        }
        /// <summary>
        /// Test the property 'TicketDelivery'
        /// </summary>
        [Fact]
        public void TicketDeliveryTest()
        {
            // TODO unit test for the property 'TicketDelivery'
        }

    }

}
