/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing Company
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompanyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Company
        //private Company instance;

        public CompanyTests()
        {
            // TODO uncomment below to create an instance of Company
            //instance = new Company();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Company
        /// </summary>
        [Fact]
        public void CompanyInstanceTest()
        {
            // TODO uncomment below to test "IsType" Company
            //Assert.IsType<Company>(instance);
        }


        /// <summary>
        /// Test the property 'Homepage'
        /// </summary>
        [Fact]
        public void HomepageTest()
        {
            // TODO unit test for the property 'Homepage'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RegistrationNumber'
        /// </summary>
        [Fact]
        public void RegistrationNumberTest()
        {
            // TODO unit test for the property 'RegistrationNumber'
        }
        /// <summary>
        /// Test the property 'RegistryLocation'
        /// </summary>
        [Fact]
        public void RegistryLocationTest()
        {
            // TODO unit test for the property 'RegistryLocation'
        }
        /// <summary>
        /// Test the property 'TaxId'
        /// </summary>
        [Fact]
        public void TaxIdTest()
        {
            // TODO unit test for the property 'TaxId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
