/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing OldCustomerType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OldCustomerTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OldCustomerType
        //private OldCustomerType instance;

        public OldCustomerTypeTests()
        {
            // TODO uncomment below to create an instance of OldCustomerType
            //instance = new OldCustomerType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OldCustomerType
        /// </summary>
        [Fact]
        public void OldCustomerTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" OldCustomerType
            //Assert.IsType<OldCustomerType>(instance);
        }



    }

}
