/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing OrderItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderItem
        //private OrderItem instance;

        public OrderItemTests()
        {
            // TODO uncomment below to create an instance of OrderItem
            //instance = new OrderItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderItem
        /// </summary>
        [Fact]
        public void OrderItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderItem
            //Assert.IsType<OrderItem>(instance);
        }


        /// <summary>
        /// Test the property 'OrderNumber'
        /// </summary>
        [Fact]
        public void OrderNumberTest()
        {
            // TODO unit test for the property 'OrderNumber'
        }
        /// <summary>
        /// Test the property 'ItemNumber'
        /// </summary>
        [Fact]
        public void ItemNumberTest()
        {
            // TODO unit test for the property 'ItemNumber'
        }
        /// <summary>
        /// Test the property 'SeatDriverWithGroup'
        /// </summary>
        [Fact]
        public void SeatDriverWithGroupTest()
        {
            // TODO unit test for the property 'SeatDriverWithGroup'
        }
        /// <summary>
        /// Test the property 'Confirmed'
        /// </summary>
        [Fact]
        public void ConfirmedTest()
        {
            // TODO unit test for the property 'Confirmed'
        }
        /// <summary>
        /// Test the property 'CanDoSteps'
        /// </summary>
        [Fact]
        public void CanDoStepsTest()
        {
            // TODO unit test for the property 'CanDoSteps'
        }
        /// <summary>
        /// Test the property 'MealDateTime'
        /// </summary>
        [Fact]
        public void MealDateTimeTest()
        {
            // TODO unit test for the property 'MealDateTime'
        }
        /// <summary>
        /// Test the property 'EventCode'
        /// </summary>
        [Fact]
        public void EventCodeTest()
        {
            // TODO unit test for the property 'EventCode'
        }
        /// <summary>
        /// Test the property 'ShowDateTime'
        /// </summary>
        [Fact]
        public void ShowDateTimeTest()
        {
            // TODO unit test for the property 'ShowDateTime'
        }
        /// <summary>
        /// Test the property 'LumpSumDiscount'
        /// </summary>
        [Fact]
        public void LumpSumDiscountTest()
        {
            // TODO unit test for the property 'LumpSumDiscount'
        }
        /// <summary>
        /// Test the property 'ItemTotalPrice'
        /// </summary>
        [Fact]
        public void ItemTotalPriceTest()
        {
            // TODO unit test for the property 'ItemTotalPrice'
        }
        /// <summary>
        /// Test the property 'OverflowCount'
        /// </summary>
        [Fact]
        public void OverflowCountTest()
        {
            // TODO unit test for the property 'OverflowCount'
        }
        /// <summary>
        /// Test the property 'OrderItemStatusCode'
        /// </summary>
        [Fact]
        public void OrderItemStatusCodeTest()
        {
            // TODO unit test for the property 'OrderItemStatusCode'
        }
        /// <summary>
        /// Test the property 'CustTanDCProfileCode'
        /// </summary>
        [Fact]
        public void CustTanDCProfileCodeTest()
        {
            // TODO unit test for the property 'CustTanDCProfileCode'
        }
        /// <summary>
        /// Test the property 'PriceListCode'
        /// </summary>
        [Fact]
        public void PriceListCodeTest()
        {
            // TODO unit test for the property 'PriceListCode'
        }
        /// <summary>
        /// Test the property 'PrintedCount'
        /// </summary>
        [Fact]
        public void PrintedCountTest()
        {
            // TODO unit test for the property 'PrintedCount'
        }
        /// <summary>
        /// Test the property 'VoucherPrinted'
        /// </summary>
        [Fact]
        public void VoucherPrintedTest()
        {
            // TODO unit test for the property 'VoucherPrinted'
        }
        /// <summary>
        /// Test the property 'CancelUserId'
        /// </summary>
        [Fact]
        public void CancelUserIdTest()
        {
            // TODO unit test for the property 'CancelUserId'
        }
        /// <summary>
        /// Test the property 'CancelDate'
        /// </summary>
        [Fact]
        public void CancelDateTest()
        {
            // TODO unit test for the property 'CancelDate'
        }
        /// <summary>
        /// Test the property 'CancelConfirmDate'
        /// </summary>
        [Fact]
        public void CancelConfirmDateTest()
        {
            // TODO unit test for the property 'CancelConfirmDate'
        }
        /// <summary>
        /// Test the property 'ConfirmDate'
        /// </summary>
        [Fact]
        public void ConfirmDateTest()
        {
            // TODO unit test for the property 'ConfirmDate'
        }
        /// <summary>
        /// Test the property 'ActiveWithOrder'
        /// </summary>
        [Fact]
        public void ActiveWithOrderTest()
        {
            // TODO unit test for the property 'ActiveWithOrder'
        }
        /// <summary>
        /// Test the property 'RestContactName'
        /// </summary>
        [Fact]
        public void RestContactNameTest()
        {
            // TODO unit test for the property 'RestContactName'
        }
        /// <summary>
        /// Test the property 'AddUserId'
        /// </summary>
        [Fact]
        public void AddUserIdTest()
        {
            // TODO unit test for the property 'AddUserId'
        }
        /// <summary>
        /// Test the property 'AddLocation'
        /// </summary>
        [Fact]
        public void AddLocationTest()
        {
            // TODO unit test for the property 'AddLocation'
        }
        /// <summary>
        /// Test the property 'AddDate'
        /// </summary>
        [Fact]
        public void AddDateTest()
        {
            // TODO unit test for the property 'AddDate'
        }
        /// <summary>
        /// Test the property 'CancelLocation'
        /// </summary>
        [Fact]
        public void CancelLocationTest()
        {
            // TODO unit test for the property 'CancelLocation'
        }
        /// <summary>
        /// Test the property 'TransFromItem'
        /// </summary>
        [Fact]
        public void TransFromItemTest()
        {
            // TODO unit test for the property 'TransFromItem'
        }
        /// <summary>
        /// Test the property 'TransToItem'
        /// </summary>
        [Fact]
        public void TransToItemTest()
        {
            // TODO unit test for the property 'TransToItem'
        }
        /// <summary>
        /// Test the property 'ItemType'
        /// </summary>
        [Fact]
        public void ItemTypeTest()
        {
            // TODO unit test for the property 'ItemType'
        }
        /// <summary>
        /// Test the property 'EventDateTime'
        /// </summary>
        [Fact]
        public void EventDateTimeTest()
        {
            // TODO unit test for the property 'EventDateTime'
        }
        /// <summary>
        /// Test the property 'VoucherExpirationDate'
        /// </summary>
        [Fact]
        public void VoucherExpirationDateTest()
        {
            // TODO unit test for the property 'VoucherExpirationDate'
        }
        /// <summary>
        /// Test the property 'BusCount'
        /// </summary>
        [Fact]
        public void BusCountTest()
        {
            // TODO unit test for the property 'BusCount'
        }
        /// <summary>
        /// Test the property 'GivexNumber'
        /// </summary>
        [Fact]
        public void GivexNumberTest()
        {
            // TODO unit test for the property 'GivexNumber'
        }
        /// <summary>
        /// Test the property 'GivexSecurityCode'
        /// </summary>
        [Fact]
        public void GivexSecurityCodeTest()
        {
            // TODO unit test for the property 'GivexSecurityCode'
        }
        /// <summary>
        /// Test the property 'ActivateUserId'
        /// </summary>
        [Fact]
        public void ActivateUserIdTest()
        {
            // TODO unit test for the property 'ActivateUserId'
        }
        /// <summary>
        /// Test the property 'ActivateDate'
        /// </summary>
        [Fact]
        public void ActivateDateTest()
        {
            // TODO unit test for the property 'ActivateDate'
        }
        /// <summary>
        /// Test the property 'EmpBenefitCode'
        /// </summary>
        [Fact]
        public void EmpBenefitCodeTest()
        {
            // TODO unit test for the property 'EmpBenefitCode'
        }
        /// <summary>
        /// Test the property 'PartnerConfirm'
        /// </summary>
        [Fact]
        public void PartnerConfirmTest()
        {
            // TODO unit test for the property 'PartnerConfirm'
        }
        /// <summary>
        /// Test the property 'PartnerEvent'
        /// </summary>
        [Fact]
        public void PartnerEventTest()
        {
            // TODO unit test for the property 'PartnerEvent'
        }
        /// <summary>
        /// Test the property 'PluNumber'
        /// </summary>
        [Fact]
        public void PluNumberTest()
        {
            // TODO unit test for the property 'PluNumber'
        }
        /// <summary>
        /// Test the property 'SkuCode'
        /// </summary>
        [Fact]
        public void SkuCodeTest()
        {
            // TODO unit test for the property 'SkuCode'
        }
        /// <summary>
        /// Test the property 'SkuDescription'
        /// </summary>
        [Fact]
        public void SkuDescriptionTest()
        {
            // TODO unit test for the property 'SkuDescription'
        }
        /// <summary>
        /// Test the property 'SkuBinLocation'
        /// </summary>
        [Fact]
        public void SkuBinLocationTest()
        {
            // TODO unit test for the property 'SkuBinLocation'
        }
        /// <summary>
        /// Test the property 'SkuTaxType'
        /// </summary>
        [Fact]
        public void SkuTaxTypeTest()
        {
            // TODO unit test for the property 'SkuTaxType'
        }
        /// <summary>
        /// Test the property 'Sale'
        /// </summary>
        [Fact]
        public void SaleTest()
        {
            // TODO unit test for the property 'Sale'
        }
        /// <summary>
        /// Test the property 'ManDiscountCode'
        /// </summary>
        [Fact]
        public void ManDiscountCodeTest()
        {
            // TODO unit test for the property 'ManDiscountCode'
        }
        /// <summary>
        /// Test the property 'MiscSkuRef'
        /// </summary>
        [Fact]
        public void MiscSkuRefTest()
        {
            // TODO unit test for the property 'MiscSkuRef'
        }
        /// <summary>
        /// Test the property 'ShipDate'
        /// </summary>
        [Fact]
        public void ShipDateTest()
        {
            // TODO unit test for the property 'ShipDate'
        }
        /// <summary>
        /// Test the property 'TrackNumber'
        /// </summary>
        [Fact]
        public void TrackNumberTest()
        {
            // TODO unit test for the property 'TrackNumber'
        }
        /// <summary>
        /// Test the property 'Damaged'
        /// </summary>
        [Fact]
        public void DamagedTest()
        {
            // TODO unit test for the property 'Damaged'
        }
        /// <summary>
        /// Test the property 'ShipMethod'
        /// </summary>
        [Fact]
        public void ShipMethodTest()
        {
            // TODO unit test for the property 'ShipMethod'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Fact]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'ItemGrandTotalPrice'
        /// </summary>
        [Fact]
        public void ItemGrandTotalPriceTest()
        {
            // TODO unit test for the property 'ItemGrandTotalPrice'
        }
        /// <summary>
        /// Test the property 'TraDevCount'
        /// </summary>
        [Fact]
        public void TraDevCountTest()
        {
            // TODO unit test for the property 'TraDevCount'
        }
        /// <summary>
        /// Test the property 'MiscSkuDescription'
        /// </summary>
        [Fact]
        public void MiscSkuDescriptionTest()
        {
            // TODO unit test for the property 'MiscSkuDescription'
        }
        /// <summary>
        /// Test the property 'Free'
        /// </summary>
        [Fact]
        public void FreeTest()
        {
            // TODO unit test for the property 'Free'
        }
        /// <summary>
        /// Test the property 'OldPartnerConfirm'
        /// </summary>
        [Fact]
        public void OldPartnerConfirmTest()
        {
            // TODO unit test for the property 'OldPartnerConfirm'
        }
        /// <summary>
        /// Test the property 'FreeForItemNumber'
        /// </summary>
        [Fact]
        public void FreeForItemNumberTest()
        {
            // TODO unit test for the property 'FreeForItemNumber'
        }
        /// <summary>
        /// Test the property 'TraDevLangCode'
        /// </summary>
        [Fact]
        public void TraDevLangCodeTest()
        {
            // TODO unit test for the property 'TraDevLangCode'
        }
        /// <summary>
        /// Test the property 'Bus'
        /// </summary>
        [Fact]
        public void BusTest()
        {
            // TODO unit test for the property 'Bus'
        }
        /// <summary>
        /// Test the property 'TravelPhoneNumber'
        /// </summary>
        [Fact]
        public void TravelPhoneNumberTest()
        {
            // TODO unit test for the property 'TravelPhoneNumber'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'SpecialSituations'
        /// </summary>
        [Fact]
        public void SpecialSituationsTest()
        {
            // TODO unit test for the property 'SpecialSituations'
        }
        /// <summary>
        /// Test the property 'OrderItemDetails'
        /// </summary>
        [Fact]
        public void OrderItemDetailsTest()
        {
            // TODO unit test for the property 'OrderItemDetails'
        }
        /// <summary>
        /// Test the property 'Seats'
        /// </summary>
        [Fact]
        public void SeatsTest()
        {
            // TODO unit test for the property 'Seats'
        }
        /// <summary>
        /// Test the property 'OverflowSeats'
        /// </summary>
        [Fact]
        public void OverflowSeatsTest()
        {
            // TODO unit test for the property 'OverflowSeats'
        }
        /// <summary>
        /// Test the property 'ItemFees'
        /// </summary>
        [Fact]
        public void ItemFeesTest()
        {
            // TODO unit test for the property 'ItemFees'
        }
        /// <summary>
        /// Test the property 'ItemTaxes'
        /// </summary>
        [Fact]
        public void ItemTaxesTest()
        {
            // TODO unit test for the property 'ItemTaxes'
        }
        /// <summary>
        /// Test the property 'ItemComps'
        /// </summary>
        [Fact]
        public void ItemCompsTest()
        {
            // TODO unit test for the property 'ItemComps'
        }
        /// <summary>
        /// Test the property 'GroupInfo'
        /// </summary>
        [Fact]
        public void GroupInfoTest()
        {
            // TODO unit test for the property 'GroupInfo'
        }
        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }
        /// <summary>
        /// Test the property 'MiscEvent'
        /// </summary>
        [Fact]
        public void MiscEventTest()
        {
            // TODO unit test for the property 'MiscEvent'
        }
        /// <summary>
        /// Test the property 'LogActivity'
        /// </summary>
        [Fact]
        public void LogActivityTest()
        {
            // TODO unit test for the property 'LogActivity'
        }
        /// <summary>
        /// Test the property 'LogChanges'
        /// </summary>
        [Fact]
        public void LogChangesTest()
        {
            // TODO unit test for the property 'LogChanges'
        }
        /// <summary>
        /// Test the property 'SeatOverBooked'
        /// </summary>
        [Fact]
        public void SeatOverBookedTest()
        {
            // TODO unit test for the property 'SeatOverBooked'
        }
        /// <summary>
        /// Test the property 'SeatOverbookCount'
        /// </summary>
        [Fact]
        public void SeatOverbookCountTest()
        {
            // TODO unit test for the property 'SeatOverbookCount'
        }
        /// <summary>
        /// Test the property 'SendToAccpac'
        /// </summary>
        [Fact]
        public void SendToAccpacTest()
        {
            // TODO unit test for the property 'SendToAccpac'
        }
        /// <summary>
        /// Test the property 'Persisted'
        /// </summary>
        [Fact]
        public void PersistedTest()
        {
            // TODO unit test for the property 'Persisted'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'ItemCount'
        /// </summary>
        [Fact]
        public void ItemCountTest()
        {
            // TODO unit test for the property 'ItemCount'
        }
        /// <summary>
        /// Test the property 'Cancelled'
        /// </summary>
        [Fact]
        public void CancelledTest()
        {
            // TODO unit test for the property 'Cancelled'
        }
        /// <summary>
        /// Test the property 'TotalCustomerDiscount'
        /// </summary>
        [Fact]
        public void TotalCustomerDiscountTest()
        {
            // TODO unit test for the property 'TotalCustomerDiscount'
        }
        /// <summary>
        /// Test the property 'FirstOccurringFeeDate'
        /// </summary>
        [Fact]
        public void FirstOccurringFeeDateTest()
        {
            // TODO unit test for the property 'FirstOccurringFeeDate'
        }
        /// <summary>
        /// Test the property 'New'
        /// </summary>
        [Fact]
        public void NewTest()
        {
            // TODO unit test for the property 'New'
        }
        /// <summary>
        /// Test the property 'AllAssignedSeatCount'
        /// </summary>
        [Fact]
        public void AllAssignedSeatCountTest()
        {
            // TODO unit test for the property 'AllAssignedSeatCount'
        }
        /// <summary>
        /// Test the property 'TransactionChargeItem'
        /// </summary>
        [Fact]
        public void TransactionChargeItemTest()
        {
            // TODO unit test for the property 'TransactionChargeItem'
        }
        /// <summary>
        /// Test the property 'TotalFee'
        /// </summary>
        [Fact]
        public void TotalFeeTest()
        {
            // TODO unit test for the property 'TotalFee'
        }
        /// <summary>
        /// Test the property 'TaxType'
        /// </summary>
        [Fact]
        public void TaxTypeTest()
        {
            // TODO unit test for the property 'TaxType'
        }
        /// <summary>
        /// Test the property 'TotalTax'
        /// </summary>
        [Fact]
        public void TotalTaxTest()
        {
            // TODO unit test for the property 'TotalTax'
        }
        /// <summary>
        /// Test the property 'TotalGratuity'
        /// </summary>
        [Fact]
        public void TotalGratuityTest()
        {
            // TODO unit test for the property 'TotalGratuity'
        }
        /// <summary>
        /// Test the property 'TotalDesignationCount'
        /// </summary>
        [Fact]
        public void TotalDesignationCountTest()
        {
            // TODO unit test for the property 'TotalDesignationCount'
        }
        /// <summary>
        /// Test the property 'SeatedCount'
        /// </summary>
        [Fact]
        public void SeatedCountTest()
        {
            // TODO unit test for the property 'SeatedCount'
        }
        /// <summary>
        /// Test the property 'TotalDiscount'
        /// </summary>
        [Fact]
        public void TotalDiscountTest()
        {
            // TODO unit test for the property 'TotalDiscount'
        }
        /// <summary>
        /// Test the property 'PaidCount'
        /// </summary>
        [Fact]
        public void PaidCountTest()
        {
            // TODO unit test for the property 'PaidCount'
        }
        /// <summary>
        /// Test the property 'UnprintedCount'
        /// </summary>
        [Fact]
        public void UnprintedCountTest()
        {
            // TODO unit test for the property 'UnprintedCount'
        }
        /// <summary>
        /// Test the property 'CompCount'
        /// </summary>
        [Fact]
        public void CompCountTest()
        {
            // TODO unit test for the property 'CompCount'
        }
        /// <summary>
        /// Test the property 'ZonedEventDateTime'
        /// </summary>
        [Fact]
        public void ZonedEventDateTimeTest()
        {
            // TODO unit test for the property 'ZonedEventDateTime'
        }
        /// <summary>
        /// Test the property 'AssignedSeatCount'
        /// </summary>
        [Fact]
        public void AssignedSeatCountTest()
        {
            // TODO unit test for the property 'AssignedSeatCount'
        }
        /// <summary>
        /// Test the property 'ManualDiscountValue'
        /// </summary>
        [Fact]
        public void ManualDiscountValueTest()
        {
            // TODO unit test for the property 'ManualDiscountValue'
        }
        /// <summary>
        /// Test the property 'GrandTotalSavings'
        /// </summary>
        [Fact]
        public void GrandTotalSavingsTest()
        {
            // TODO unit test for the property 'GrandTotalSavings'
        }
        /// <summary>
        /// Test the property 'NetPrice'
        /// </summary>
        [Fact]
        public void NetPriceTest()
        {
            // TODO unit test for the property 'NetPrice'
        }
        /// <summary>
        /// Test the property 'TotalSavings'
        /// </summary>
        [Fact]
        public void TotalSavingsTest()
        {
            // TODO unit test for the property 'TotalSavings'
        }
        /// <summary>
        /// Test the property 'Taxable'
        /// </summary>
        [Fact]
        public void TaxableTest()
        {
            // TODO unit test for the property 'Taxable'
        }

    }

}
