/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing OrderItemComp
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderItemCompTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderItemComp
        //private OrderItemComp instance;

        public OrderItemCompTests()
        {
            // TODO uncomment below to create an instance of OrderItemComp
            //instance = new OrderItemComp();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderItemComp
        /// </summary>
        [Fact]
        public void OrderItemCompInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderItemComp
            //Assert.IsType<OrderItemComp>(instance);
        }


        /// <summary>
        /// Test the property 'OrderNumber'
        /// </summary>
        [Fact]
        public void OrderNumberTest()
        {
            // TODO unit test for the property 'OrderNumber'
        }
        /// <summary>
        /// Test the property 'ItemNumber'
        /// </summary>
        [Fact]
        public void ItemNumberTest()
        {
            // TODO unit test for the property 'ItemNumber'
        }
        /// <summary>
        /// Test the property 'CompNumber'
        /// </summary>
        [Fact]
        public void CompNumberTest()
        {
            // TODO unit test for the property 'CompNumber'
        }
        /// <summary>
        /// Test the property 'EventCode'
        /// </summary>
        [Fact]
        public void EventCodeTest()
        {
            // TODO unit test for the property 'EventCode'
        }
        /// <summary>
        /// Test the property 'CompType'
        /// </summary>
        [Fact]
        public void CompTypeTest()
        {
            // TODO unit test for the property 'CompType'
        }
        /// <summary>
        /// Test the property 'UniqueCode'
        /// </summary>
        [Fact]
        public void UniqueCodeTest()
        {
            // TODO unit test for the property 'UniqueCode'
        }
        /// <summary>
        /// Test the property 'AddUserId'
        /// </summary>
        [Fact]
        public void AddUserIdTest()
        {
            // TODO unit test for the property 'AddUserId'
        }
        /// <summary>
        /// Test the property 'AddDate'
        /// </summary>
        [Fact]
        public void AddDateTest()
        {
            // TODO unit test for the property 'AddDate'
        }
        /// <summary>
        /// Test the property 'Adult'
        /// </summary>
        [Fact]
        public void AdultTest()
        {
            // TODO unit test for the property 'Adult'
        }
        /// <summary>
        /// Test the property 'Teen'
        /// </summary>
        [Fact]
        public void TeenTest()
        {
            // TODO unit test for the property 'Teen'
        }
        /// <summary>
        /// Test the property 'Child'
        /// </summary>
        [Fact]
        public void ChildTest()
        {
            // TODO unit test for the property 'Child'
        }
        /// <summary>
        /// Test the property 'DiscountPercent'
        /// </summary>
        [Fact]
        public void DiscountPercentTest()
        {
            // TODO unit test for the property 'DiscountPercent'
        }
        /// <summary>
        /// Test the property 'DiscCountMax'
        /// </summary>
        [Fact]
        public void DiscCountMaxTest()
        {
            // TODO unit test for the property 'DiscCountMax'
        }
        /// <summary>
        /// Test the property 'OrderItem'
        /// </summary>
        [Fact]
        public void OrderItemTest()
        {
            // TODO unit test for the property 'OrderItem'
        }

    }

}
