/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing OrderItemDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderItemDetailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderItemDetail
        //private OrderItemDetail instance;

        public OrderItemDetailTests()
        {
            // TODO uncomment below to create an instance of OrderItemDetail
            //instance = new OrderItemDetail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderItemDetail
        /// </summary>
        [Fact]
        public void OrderItemDetailInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderItemDetail
            //Assert.IsType<OrderItemDetail>(instance);
        }


        /// <summary>
        /// Test the property 'OrderNumber'
        /// </summary>
        [Fact]
        public void OrderNumberTest()
        {
            // TODO unit test for the property 'OrderNumber'
        }
        /// <summary>
        /// Test the property 'ItemNumber'
        /// </summary>
        [Fact]
        public void ItemNumberTest()
        {
            // TODO unit test for the property 'ItemNumber'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'ManDiscountCount'
        /// </summary>
        [Fact]
        public void ManDiscountCountTest()
        {
            // TODO unit test for the property 'ManDiscountCount'
        }
        /// <summary>
        /// Test the property 'SpecialDiscountCount'
        /// </summary>
        [Fact]
        public void SpecialDiscountCountTest()
        {
            // TODO unit test for the property 'SpecialDiscountCount'
        }
        /// <summary>
        /// Test the property 'DesignationCode'
        /// </summary>
        [Fact]
        public void DesignationCodeTest()
        {
            // TODO unit test for the property 'DesignationCode'
        }
        /// <summary>
        /// Test the property 'SeatDiscountCount'
        /// </summary>
        [Fact]
        public void SeatDiscountCountTest()
        {
            // TODO unit test for the property 'SeatDiscountCount'
        }
        /// <summary>
        /// Test the property 'SeatDiscountAmount'
        /// </summary>
        [Fact]
        public void SeatDiscountAmountTest()
        {
            // TODO unit test for the property 'SeatDiscountAmount'
        }
        /// <summary>
        /// Test the property 'CustDiscountTypeCode'
        /// </summary>
        [Fact]
        public void CustDiscountTypeCodeTest()
        {
            // TODO unit test for the property 'CustDiscountTypeCode'
        }
        /// <summary>
        /// Test the property 'CustDiscountValue'
        /// </summary>
        [Fact]
        public void CustDiscountValueTest()
        {
            // TODO unit test for the property 'CustDiscountValue'
        }
        /// <summary>
        /// Test the property 'SpecialTypeCode'
        /// </summary>
        [Fact]
        public void SpecialTypeCodeTest()
        {
            // TODO unit test for the property 'SpecialTypeCode'
        }
        /// <summary>
        /// Test the property 'SpecialDiscountValue'
        /// </summary>
        [Fact]
        public void SpecialDiscountValueTest()
        {
            // TODO unit test for the property 'SpecialDiscountValue'
        }
        /// <summary>
        /// Test the property 'ManDiscountTypeCode'
        /// </summary>
        [Fact]
        public void ManDiscountTypeCodeTest()
        {
            // TODO unit test for the property 'ManDiscountTypeCode'
        }
        /// <summary>
        /// Test the property 'ManDiscountValue'
        /// </summary>
        [Fact]
        public void ManDiscountValueTest()
        {
            // TODO unit test for the property 'ManDiscountValue'
        }
        /// <summary>
        /// Test the property 'ConfirmedCount'
        /// </summary>
        [Fact]
        public void ConfirmedCountTest()
        {
            // TODO unit test for the property 'ConfirmedCount'
        }
        /// <summary>
        /// Test the property 'TotalPrice'
        /// </summary>
        [Fact]
        public void TotalPriceTest()
        {
            // TODO unit test for the property 'TotalPrice'
        }
        /// <summary>
        /// Test the property 'SpecialDiscountTotalAmount'
        /// </summary>
        [Fact]
        public void SpecialDiscountTotalAmountTest()
        {
            // TODO unit test for the property 'SpecialDiscountTotalAmount'
        }
        /// <summary>
        /// Test the property 'ManDiscountTotalAmount'
        /// </summary>
        [Fact]
        public void ManDiscountTotalAmountTest()
        {
            // TODO unit test for the property 'ManDiscountTotalAmount'
        }
        /// <summary>
        /// Test the property 'SeatDiscountTotalAmount'
        /// </summary>
        [Fact]
        public void SeatDiscountTotalAmountTest()
        {
            // TODO unit test for the property 'SeatDiscountTotalAmount'
        }
        /// <summary>
        /// Test the property 'CustDiscountTotalAmount'
        /// </summary>
        [Fact]
        public void CustDiscountTotalAmountTest()
        {
            // TODO unit test for the property 'CustDiscountTotalAmount'
        }
        /// <summary>
        /// Test the property 'PrintedCount'
        /// </summary>
        [Fact]
        public void PrintedCountTest()
        {
            // TODO unit test for the property 'PrintedCount'
        }
        /// <summary>
        /// Test the property 'PriceValue'
        /// </summary>
        [Fact]
        public void PriceValueTest()
        {
            // TODO unit test for the property 'PriceValue'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'CompCount'
        /// </summary>
        [Fact]
        public void CompCountTest()
        {
            // TODO unit test for the property 'CompCount'
        }
        /// <summary>
        /// Test the property 'Gratuity'
        /// </summary>
        [Fact]
        public void GratuityTest()
        {
            // TODO unit test for the property 'Gratuity'
        }
        /// <summary>
        /// Test the property 'SsMargin'
        /// </summary>
        [Fact]
        public void SsMarginTest()
        {
            // TODO unit test for the property 'SsMargin'
        }
        /// <summary>
        /// Test the property 'CustDiscountCount'
        /// </summary>
        [Fact]
        public void CustDiscountCountTest()
        {
            // TODO unit test for the property 'CustDiscountCount'
        }
        /// <summary>
        /// Test the property 'OrderItem'
        /// </summary>
        [Fact]
        public void OrderItemTest()
        {
            // TODO unit test for the property 'OrderItem'
        }
        /// <summary>
        /// Test the property 'DeltaCount'
        /// </summary>
        [Fact]
        public void DeltaCountTest()
        {
            // TODO unit test for the property 'DeltaCount'
        }
        /// <summary>
        /// Test the property 'Persisted'
        /// </summary>
        [Fact]
        public void PersistedTest()
        {
            // TODO unit test for the property 'Persisted'
        }
        /// <summary>
        /// Test the property 'New'
        /// </summary>
        [Fact]
        public void NewTest()
        {
            // TODO unit test for the property 'New'
        }
        /// <summary>
        /// Test the property 'ListPriceWithDiscounts'
        /// </summary>
        [Fact]
        public void ListPriceWithDiscountsTest()
        {
            // TODO unit test for the property 'ListPriceWithDiscounts'
        }
        /// <summary>
        /// Test the property 'TotalDiscount'
        /// </summary>
        [Fact]
        public void TotalDiscountTest()
        {
            // TODO unit test for the property 'TotalDiscount'
        }
        /// <summary>
        /// Test the property 'UnprintedCount'
        /// </summary>
        [Fact]
        public void UnprintedCountTest()
        {
            // TODO unit test for the property 'UnprintedCount'
        }
        /// <summary>
        /// Test the property 'ManDiscountDollarAmount'
        /// </summary>
        [Fact]
        public void ManDiscountDollarAmountTest()
        {
            // TODO unit test for the property 'ManDiscountDollarAmount'
        }
        /// <summary>
        /// Test the property 'Savings'
        /// </summary>
        [Fact]
        public void SavingsTest()
        {
            // TODO unit test for the property 'Savings'
        }
        /// <summary>
        /// Test the property 'TotalSavings'
        /// </summary>
        [Fact]
        public void TotalSavingsTest()
        {
            // TODO unit test for the property 'TotalSavings'
        }

    }

}
