/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCompleteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCompleteResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCompleteResponse
        //private OrderCompleteResponse instance;

        public OrderCompleteResponseTests()
        {
            // TODO uncomment below to create an instance of OrderCompleteResponse
            //instance = new OrderCompleteResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCompleteResponse
        /// </summary>
        [Fact]
        public void OrderCompleteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCompleteResponse
            //Assert.IsType<OrderCompleteResponse>(instance);
        }


        /// <summary>
        /// Test the property 'PaymentAppliedInfo'
        /// </summary>
        [Fact]
        public void PaymentAppliedInfoTest()
        {
            // TODO unit test for the property 'PaymentAppliedInfo'
        }
        /// <summary>
        /// Test the property 'TicketDeliveryMsg'
        /// </summary>
        [Fact]
        public void TicketDeliveryMsgTest()
        {
            // TODO unit test for the property 'TicketDeliveryMsg'
        }
        /// <summary>
        /// Test the property 'TicketDeliveryMessage'
        /// </summary>
        [Fact]
        public void TicketDeliveryMessageTest()
        {
            // TODO unit test for the property 'TicketDeliveryMessage'
        }
        /// <summary>
        /// Test the property 'Cart'
        /// </summary>
        [Fact]
        public void CartTest()
        {
            // TODO unit test for the property 'Cart'
        }
        /// <summary>
        /// Test the property 'ETicketLink'
        /// </summary>
        [Fact]
        public void ETicketLinkTest()
        {
            // TODO unit test for the property 'ETicketLink'
        }

    }

}
