/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCompleteRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCompleteRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCompleteRequest
        //private OrderCompleteRequest instance;

        public OrderCompleteRequestTests()
        {
            // TODO uncomment below to create an instance of OrderCompleteRequest
            //instance = new OrderCompleteRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCompleteRequest
        /// </summary>
        [Fact]
        public void OrderCompleteRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCompleteRequest
            //Assert.IsType<OrderCompleteRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Cart'
        /// </summary>
        [Fact]
        public void CartTest()
        {
            // TODO unit test for the property 'Cart'
        }
        /// <summary>
        /// Test the property 'Delivery'
        /// </summary>
        [Fact]
        public void DeliveryTest()
        {
            // TODO unit test for the property 'Delivery'
        }
        /// <summary>
        /// Test the property 'Payment'
        /// </summary>
        [Fact]
        public void PaymentTest()
        {
            // TODO unit test for the property 'Payment'
        }
        /// <summary>
        /// Test the property 'SeatLockToken'
        /// </summary>
        [Fact]
        public void SeatLockTokenTest()
        {
            // TODO unit test for the property 'SeatLockToken'
        }
        /// <summary>
        /// Test the property 'OverflowSeatCount'
        /// </summary>
        [Fact]
        public void OverflowSeatCountTest()
        {
            // TODO unit test for the property 'OverflowSeatCount'
        }
        /// <summary>
        /// Test the property 'EmailList'
        /// </summary>
        [Fact]
        public void EmailListTest()
        {
            // TODO unit test for the property 'EmailList'
        }
        /// <summary>
        /// Test the property 'SameGroupConfirm'
        /// </summary>
        [Fact]
        public void SameGroupConfirmTest()
        {
            // TODO unit test for the property 'SameGroupConfirm'
        }

    }

}
