/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing OrderTicketDeliveryRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderTicketDeliveryRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderTicketDeliveryRequest
        //private OrderTicketDeliveryRequest instance;

        public OrderTicketDeliveryRequestTests()
        {
            // TODO uncomment below to create an instance of OrderTicketDeliveryRequest
            //instance = new OrderTicketDeliveryRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderTicketDeliveryRequest
        /// </summary>
        [Fact]
        public void OrderTicketDeliveryRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderTicketDeliveryRequest
            //Assert.IsType<OrderTicketDeliveryRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

    }

}
