/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing PaperCheckRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaperCheckRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaperCheckRequest
        //private PaperCheckRequest instance;

        public PaperCheckRequestTests()
        {
            // TODO uncomment below to create an instance of PaperCheckRequest
            //instance = new PaperCheckRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaperCheckRequest
        /// </summary>
        [Fact]
        public void PaperCheckRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaperCheckRequest
            //Assert.IsType<PaperCheckRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CheckAmount'
        /// </summary>
        [Fact]
        public void CheckAmountTest()
        {
            // TODO unit test for the property 'CheckAmount'
        }
        /// <summary>
        /// Test the property 'CheckNumber'
        /// </summary>
        [Fact]
        public void CheckNumberTest()
        {
            // TODO unit test for the property 'CheckNumber'
        }
        /// <summary>
        /// Test the property 'Ach'
        /// </summary>
        [Fact]
        public void AchTest()
        {
            // TODO unit test for the property 'Ach'
        }

    }

}
