/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing ReceiptDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReceiptDetailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReceiptDetail
        //private ReceiptDetail instance;

        public ReceiptDetailTests()
        {
            // TODO uncomment below to create an instance of ReceiptDetail
            //instance = new ReceiptDetail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReceiptDetail
        /// </summary>
        [Fact]
        public void ReceiptDetailInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReceiptDetail
            //Assert.IsType<ReceiptDetail>(instance);
        }


        /// <summary>
        /// Test the property 'ReceiptNumber'
        /// </summary>
        [Fact]
        public void ReceiptNumberTest()
        {
            // TODO unit test for the property 'ReceiptNumber'
        }
        /// <summary>
        /// Test the property 'SeqNumber'
        /// </summary>
        [Fact]
        public void SeqNumberTest()
        {
            // TODO unit test for the property 'SeqNumber'
        }
        /// <summary>
        /// Test the property 'ReceiptCompany'
        /// </summary>
        [Fact]
        public void ReceiptCompanyTest()
        {
            // TODO unit test for the property 'ReceiptCompany'
        }
        /// <summary>
        /// Test the property 'ReceiptDetailStatus'
        /// </summary>
        [Fact]
        public void ReceiptDetailStatusTest()
        {
            // TODO unit test for the property 'ReceiptDetailStatus'
        }
        /// <summary>
        /// Test the property 'ReceiptDetailAmount'
        /// </summary>
        [Fact]
        public void ReceiptDetailAmountTest()
        {
            // TODO unit test for the property 'ReceiptDetailAmount'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'CreditSegment1'
        /// </summary>
        [Fact]
        public void CreditSegment1Test()
        {
            // TODO unit test for the property 'CreditSegment1'
        }
        /// <summary>
        /// Test the property 'CreditSegment2'
        /// </summary>
        [Fact]
        public void CreditSegment2Test()
        {
            // TODO unit test for the property 'CreditSegment2'
        }
        /// <summary>
        /// Test the property 'CreditSegment3'
        /// </summary>
        [Fact]
        public void CreditSegment3Test()
        {
            // TODO unit test for the property 'CreditSegment3'
        }
        /// <summary>
        /// Test the property 'CreditSegment4'
        /// </summary>
        [Fact]
        public void CreditSegment4Test()
        {
            // TODO unit test for the property 'CreditSegment4'
        }
        /// <summary>
        /// Test the property 'CreditSegment5'
        /// </summary>
        [Fact]
        public void CreditSegment5Test()
        {
            // TODO unit test for the property 'CreditSegment5'
        }
        /// <summary>
        /// Test the property 'DebitSegment1'
        /// </summary>
        [Fact]
        public void DebitSegment1Test()
        {
            // TODO unit test for the property 'DebitSegment1'
        }
        /// <summary>
        /// Test the property 'DebitSegment2'
        /// </summary>
        [Fact]
        public void DebitSegment2Test()
        {
            // TODO unit test for the property 'DebitSegment2'
        }
        /// <summary>
        /// Test the property 'DebitSegment3'
        /// </summary>
        [Fact]
        public void DebitSegment3Test()
        {
            // TODO unit test for the property 'DebitSegment3'
        }
        /// <summary>
        /// Test the property 'DebitSegment4'
        /// </summary>
        [Fact]
        public void DebitSegment4Test()
        {
            // TODO unit test for the property 'DebitSegment4'
        }
        /// <summary>
        /// Test the property 'DebitSegment5'
        /// </summary>
        [Fact]
        public void DebitSegment5Test()
        {
            // TODO unit test for the property 'DebitSegment5'
        }
        /// <summary>
        /// Test the property 'InvoiceCompany'
        /// </summary>
        [Fact]
        public void InvoiceCompanyTest()
        {
            // TODO unit test for the property 'InvoiceCompany'
        }
        /// <summary>
        /// Test the property 'InvoiceNumber'
        /// </summary>
        [Fact]
        public void InvoiceNumberTest()
        {
            // TODO unit test for the property 'InvoiceNumber'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'GltNumber'
        /// </summary>
        [Fact]
        public void GltNumberTest()
        {
            // TODO unit test for the property 'GltNumber'
        }
        /// <summary>
        /// Test the property 'GltCompany'
        /// </summary>
        [Fact]
        public void GltCompanyTest()
        {
            // TODO unit test for the property 'GltCompany'
        }
        /// <summary>
        /// Test the property 'ModifyDate'
        /// </summary>
        [Fact]
        public void ModifyDateTest()
        {
            // TODO unit test for the property 'ModifyDate'
        }
        /// <summary>
        /// Test the property 'Receipt'
        /// </summary>
        [Fact]
        public void ReceiptTest()
        {
            // TODO unit test for the property 'Receipt'
        }
        /// <summary>
        /// Test the property 'Invoice'
        /// </summary>
        [Fact]
        public void InvoiceTest()
        {
            // TODO unit test for the property 'Invoice'
        }

    }

}
