/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing Schedule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Schedule
        //private Schedule instance;

        public ScheduleTests()
        {
            // TODO uncomment below to create an instance of Schedule
            //instance = new Schedule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Schedule
        /// </summary>
        [Fact]
        public void ScheduleInstanceTest()
        {
            // TODO uncomment below to test "IsType" Schedule
            //Assert.IsType<Schedule>(instance);
        }


        /// <summary>
        /// Test the property 'EventCode'
        /// </summary>
        [Fact]
        public void EventCodeTest()
        {
            // TODO unit test for the property 'EventCode'
        }
        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Fact]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }
        /// <summary>
        /// Test the property 'SeatsAvailable'
        /// </summary>
        [Fact]
        public void SeatsAvailableTest()
        {
            // TODO unit test for the property 'SeatsAvailable'
        }
        /// <summary>
        /// Test the property 'SeatsBooked'
        /// </summary>
        [Fact]
        public void SeatsBookedTest()
        {
            // TODO unit test for the property 'SeatsBooked'
        }
        /// <summary>
        /// Test the property 'SeatsBlocked'
        /// </summary>
        [Fact]
        public void SeatsBlockedTest()
        {
            // TODO unit test for the property 'SeatsBlocked'
        }
        /// <summary>
        /// Test the property 'SeatsOverflow'
        /// </summary>
        [Fact]
        public void SeatsOverflowTest()
        {
            // TODO unit test for the property 'SeatsOverflow'
        }
        /// <summary>
        /// Test the property 'SeatingTemplateCode'
        /// </summary>
        [Fact]
        public void SeatingTemplateCodeTest()
        {
            // TODO unit test for the property 'SeatingTemplateCode'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'PriceListCode'
        /// </summary>
        [Fact]
        public void PriceListCodeTest()
        {
            // TODO unit test for the property 'PriceListCode'
        }
        /// <summary>
        /// Test the property 'SeatsOverbooked'
        /// </summary>
        [Fact]
        public void SeatsOverbookedTest()
        {
            // TODO unit test for the property 'SeatsOverbooked'
        }
        /// <summary>
        /// Test the property 'AllowQtoDiscount'
        /// </summary>
        [Fact]
        public void AllowQtoDiscountTest()
        {
            // TODO unit test for the property 'AllowQtoDiscount'
        }
        /// <summary>
        /// Test the property 'CustTandcProfileCode'
        /// </summary>
        [Fact]
        public void CustTandcProfileCodeTest()
        {
            // TODO unit test for the property 'CustTandcProfileCode'
        }
        /// <summary>
        /// Test the property 'HeldCount'
        /// </summary>
        [Fact]
        public void HeldCountTest()
        {
            // TODO unit test for the property 'HeldCount'
        }
        /// <summary>
        /// Test the property 'WheelChairCount'
        /// </summary>
        [Fact]
        public void WheelChairCountTest()
        {
            // TODO unit test for the property 'WheelChairCount'
        }
        /// <summary>
        /// Test the property 'BlackoutUpdateSent'
        /// </summary>
        [Fact]
        public void BlackoutUpdateSentTest()
        {
            // TODO unit test for the property 'BlackoutUpdateSent'
        }
        /// <summary>
        /// Test the property 'BlackoutUpdateDatetime'
        /// </summary>
        [Fact]
        public void BlackoutUpdateDatetimeTest()
        {
            // TODO unit test for the property 'BlackoutUpdateDatetime'
        }
        /// <summary>
        /// Test the property 'TraDevCount'
        /// </summary>
        [Fact]
        public void TraDevCountTest()
        {
            // TODO unit test for the property 'TraDevCount'
        }
        /// <summary>
        /// Test the property 'HdShoot'
        /// </summary>
        [Fact]
        public void HdShootTest()
        {
            // TODO unit test for the property 'HdShoot'
        }
        /// <summary>
        /// Test the property 'CmsAnnouncement'
        /// </summary>
        [Fact]
        public void CmsAnnouncementTest()
        {
            // TODO unit test for the property 'CmsAnnouncement'
        }
        /// <summary>
        /// Test the property 'DenyApplicationCode'
        /// </summary>
        [Fact]
        public void DenyApplicationCodeTest()
        {
            // TODO unit test for the property 'DenyApplicationCode'
        }
        /// <summary>
        /// Test the property 'Cancelled'
        /// </summary>
        [Fact]
        public void CancelledTest()
        {
            // TODO unit test for the property 'Cancelled'
        }
        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }

    }

}
