/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing SpecialType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpecialTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpecialType
        //private SpecialType instance;

        public SpecialTypeTests()
        {
            // TODO uncomment below to create an instance of SpecialType
            //instance = new SpecialType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpecialType
        /// </summary>
        [Fact]
        public void SpecialTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpecialType
            //Assert.IsType<SpecialType>(instance);
        }


        /// <summary>
        /// Test the property 'SpecialCode'
        /// </summary>
        [Fact]
        public void SpecialCodeTest()
        {
            // TODO unit test for the property 'SpecialCode'
        }
        /// <summary>
        /// Test the property 'CorpAffilCode'
        /// </summary>
        [Fact]
        public void CorpAffilCodeTest()
        {
            // TODO unit test for the property 'CorpAffilCode'
        }
        /// <summary>
        /// Test the property 'CustTypeCode'
        /// </summary>
        [Fact]
        public void CustTypeCodeTest()
        {
            // TODO unit test for the property 'CustTypeCode'
        }
        /// <summary>
        /// Test the property 'Special'
        /// </summary>
        [Fact]
        public void SpecialTest()
        {
            // TODO unit test for the property 'Special'
        }

    }

}
