/*
 * Partner Ticketing API
 *
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SightSound.TicketingSDK.Api;
using SightSound.TicketingSDK.Model;
using SightSound.TicketingSDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SightSound.TicketingSDK.Test.Model
{
    /// <summary>
    ///  Class for testing SpecialAssociatedEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpecialAssociatedEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpecialAssociatedEvent
        //private SpecialAssociatedEvent instance;

        public SpecialAssociatedEventTests()
        {
            // TODO uncomment below to create an instance of SpecialAssociatedEvent
            //instance = new SpecialAssociatedEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpecialAssociatedEvent
        /// </summary>
        [Fact]
        public void SpecialAssociatedEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpecialAssociatedEvent
            //Assert.IsType<SpecialAssociatedEvent>(instance);
        }


        /// <summary>
        /// Test the property 'SpecialCode'
        /// </summary>
        [Fact]
        public void SpecialCodeTest()
        {
            // TODO unit test for the property 'SpecialCode'
        }
        /// <summary>
        /// Test the property 'EventCode'
        /// </summary>
        [Fact]
        public void EventCodeTest()
        {
            // TODO unit test for the property 'EventCode'
        }
        /// <summary>
        /// Test the property 'SpecialRangeStartDate'
        /// </summary>
        [Fact]
        public void SpecialRangeStartDateTest()
        {
            // TODO unit test for the property 'SpecialRangeStartDate'
        }
        /// <summary>
        /// Test the property 'SpecialRangeEndDate'
        /// </summary>
        [Fact]
        public void SpecialRangeEndDateTest()
        {
            // TODO unit test for the property 'SpecialRangeEndDate'
        }
        /// <summary>
        /// Test the property 'ComboEventNumber'
        /// </summary>
        [Fact]
        public void ComboEventNumberTest()
        {
            // TODO unit test for the property 'ComboEventNumber'
        }
        /// <summary>
        /// Test the property 'Special'
        /// </summary>
        [Fact]
        public void SpecialTest()
        {
            // TODO unit test for the property 'Special'
        }

    }

}
